- menu_name: "Links"

- name: "ProStyle"
  url: "http://prostyle.io"
  title: "ProStyle"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS"

- name: "Sitemap"
  url: "/sitemap.xml"
  title: "Sitemap"
